import { Img } from "./Img";
import { Text } from "./Text";
import { Heading } from "./Heading";
import { Button } from "./Button";
import { Input } from "./Input";
import { Input2 } from "./Input2";
import { Button2 } from "./Button2";
import { CheckBox } from "./CheckBox";
import { StatefulInput2 } from "./StatefulInput2";
export { Img, Text, Heading, Button, Input, Input2, Button2,CheckBox, StatefulInput2  };
